AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        zipcode:
            type: integer
    lifecycleCallbacks: {  }

    oneToMany:
        products:
            targetEntity: Product
            mappedBy: user

    oneToMany:
        ratingusers:
            targetEntity: Ratinguser
            mappedBy: user