<?php

namespace AppBundle\Repository;

/**
 * RatinguserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatinguserRepository extends \Doctrine\ORM\EntityRepository
{
}
