<?php

namespace AppBundle\Repository;

/**
 * RatingproductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingproductRepository extends \Doctrine\ORM\EntityRepository
{
	
}
